'use client';
import {useEffect,useMemo,useState} from 'react';
import {Box,Camera,Download,FolderOpen,Smartphone} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {CapturePackage} from '@/lib/recruiser/capture-package';

function useBlobUrl(blob:Blob|undefined){
 const[url,setUrl]=useState('');
 useEffect(()=>{if(!blob){setUrl('');return}const next=URL.createObjectURL(blob);setUrl(next);return()=>URL.revokeObjectURL(next)},[blob]);return url;
}
function relativeTime(timestamp:string,origin:string){const delta=BigInt(timestamp)-BigInt(origin),negative=delta<BigInt('0'),value=negative?-delta:delta;return(negative?'-':'+')+(value/BigInt('1000000000')).toString()+'.'+((value%BigInt('1000000000'))/BigInt('1000000')).toString().padStart(3,'0')+' s'}

export function CaptureInformation({open,onClose,onOpenPackage}:{open:boolean;onClose:()=>void;onOpenPackage:()=>void}){
 return <Dialog open={open} onOpenChange={value=>{if(!value)onClose()}}><DialogContent className="capture-package-dialog"><DialogHeader><DialogTitle>Capture surroundings</DialogTitle><DialogDescription>Use Recruiser Capture on Android to scan the room around you.</DialogDescription></DialogHeader><div className="capture-native-intro"><Smartphone size={32}/><p>The Android app provides a live camera viewfinder, tracking and available depth. Capture your observations first, then choose <strong>Build 3D on this device</strong> in the app.</p></div><p className="muted">This browser is your portable viewer. It cannot open ARCore or check whether the Android app is installed. Export a capture package from the Android app, then open it here to review saved imagery, timing and reconstructed scenes.</p><button className="primary full" onClick={onOpenPackage}><FolderOpen size={17}/>Open capture package</button><p className="small muted">Choose a .recruiser-capture.zip file. Review and local PLY viewing work without a reconstruction server. Audio is not part of this capture milestone.</p></DialogContent></Dialog>;
}

export default function CapturePackageReview({capture,onClose,onOpenScene}:{capture:CapturePackage;onClose:()=>void;onOpenScene:(file:File)=>void}){
 const{manifest,frames,imu,events,quality,assets}=capture;
 const[frameIndex,setFrameIndex]=useState(0),[segmentIndex,setSegmentIndex]=useState(0),[videoFailed,setVideoFailed]=useState(false),[imageFailed,setImageFailed]=useState(false);
 const frame=frames[frameIndex],segment=manifest.segments[segmentIndex],frameUrl=useBlobUrl(frame?.image?assets.get(frame.image.path):undefined),videoUrl=useBlobUrl(segment?assets.get(segment.path):undefined),originalUrl=useBlobUrl(capture.original);
 useEffect(()=>setVideoFailed(false),[videoUrl]);useEffect(()=>setImageFailed(false),[frameUrl]);
 const depthCount=useMemo(()=>frames.filter(f=>f.depth).length,[frames]);
 const findings=useMemo(()=>quality.filter(q=>q.frameId===frame?.id).flatMap(q=>q.findings),[quality,frame?.id]);
 const gaps=useMemo(()=>events.filter(e=>/gap|interrupt|unavail|lost|drop|pause|recover|unalign|reset/i.test(e.type)),[events]);
 const cameraClock=manifest.clocks.find(c=>c.id==='arcore-camera'),imuClock=manifest.clocks.find(c=>c.id==='android-elapsed');
 const origin=frames[0]?.timestampNs??manifest.segments[0]?.startTimestampNs??'0';
 const aligned=imuClock?.offsetToSessionNs!==null&&imuClock?.offsetToSessionNs!==undefined;
 return <Dialog open onOpenChange={value=>{if(!value)onClose()}}><DialogContent className="capture-package-dialog"><DialogHeader><DialogTitle>Recorded capture session</DialogTitle><DialogDescription>{manifest.provider.device} · {new Date(manifest.createdAt).toLocaleString()} · {manifest.state}</DialogDescription></DialogHeader>
  <div className="capture-package-counts" aria-label="Recorded observations">{[[frames.length,'Frames'],[imu.length,'IMU samples'],[depthCount,'Depth maps'],[manifest.calibrations.length,'Calibrations']].map(([count,label])=><div key={label}><strong>{count.toLocaleString()}</strong><span>{label}</span></div>)}</div>
  <p className="small muted">The original archive and all observations are saved together on this device. Review does not activate the camera or send data to a processing service.</p>
  {(!frames.length||manifest.state==='interrupted')&&<p className="notice">{!frames.length?'This package contains no retained camera frames. Available recordings and event history remain below.':'This session was interrupted. Its retained observations are available; gaps are not filled in.'}</p>}
  {frame&&<section className="capture-package-section"><h3><Camera size={17}/>Saved camera observations</h3><div className="media-preview">{frameUrl&&!imageFailed?<img key={frameUrl} src={frameUrl} alt={'Retained camera frame '+frame.id} onError={()=>setImageFailed(true)}/>:<p className="notice">{imageFailed?'This retained image cannot be decoded by the browser.':'No aligned camera image was retained for this frame.'}</p>}</div><label className="field">Frame {frameIndex+1} of {frames.length}<input aria-label="Recorded frame" type="range" min={0} max={frames.length-1} value={frameIndex} onChange={e=>setFrameIndex(Number(e.target.value))}/></label><div className="capture-package-metadata"><span>{relativeTime(frame.timestampNs,origin)} · {frame.tracking}</span><span>Depth: {frame.depth?(frame.depth.stale?'stale · excluded from fusion':'retained'):'unavailable'}</span><span>Pose: {frame.pose?'retained':'unknown'}</span><span>World frame: {frame.worldFrameId}</span></div>{frame.trackingFailure&&<p className="amber small">Tracking: {frame.trackingFailure}</p>}{findings.map((finding,i)=><p className={finding.severity==='warning'?'amber small':'small muted'} key={finding.code+i}>{finding.message}</p>)}<p className="small muted">Quality checks are provisional. Frame overlap is not a complete surface-coverage map.</p></section>}
  {!!manifest.segments.length&&<section className="capture-package-section"><h3>Original recordings</h3><label className="field">Recording segment<select value={segmentIndex} onChange={e=>setSegmentIndex(Number(e.target.value))}>{manifest.segments.map((s,i)=><option value={i} key={s.id}>{i+1} · {s.state} · {s.width} × {s.height}</option>)}</select></label>{videoUrl&&!videoFailed?<video key={videoUrl} className="capture-package-video" src={videoUrl} controls preload="metadata" playsInline onError={()=>setVideoFailed(true)}/>:<p className="notice">This browser cannot decode the ARCore recording. Replay the original session in Recruiser Capture on Android.</p>}<p className="small muted">Browser video playback shows recorded imagery only. ARCore tracking playback requires the Android app; replayed poses do not replace the originals.</p></section>}
  <section className="capture-package-section"><h3>Sensor timing and gaps</h3><p className="small">Camera clock: {cameraClock?.offsetToSessionNs!==null&&cameraClock?.offsetToSessionNs!==undefined?'mapped to session time':'mapping unknown'}. IMU: {aligned?'mapped to session time':'unaligned — clock mapping unknown'}.</p>{manifest.clocks.map(clock=><p className="small muted" key={clock.id}>{clock.id}: {clock.source}. Timing uncertainty: {clock.uncertaintyNs===null?'unknown':clock.uncertaintyNs+' ns'}.</p>)}<p className="small muted">GPS/location: {manifest.capabilities.location?'declared available; no location stream in this version':'not captured'}. Depth: {manifest.capabilities.depth?'supported; individual frames may lack samples':'unavailable'}.</p>{!!imu.length&&<details><summary>IMU sample timeline · first {Math.min(imu.length,50)} of {imu.length.toLocaleString()}</summary><div className="capture-package-table"><table><thead><tr><th>Sensor</th><th>{aligned?'Session time':'Android elapsed time (ns)'}</th><th>Values</th></tr></thead><tbody>{imu.slice(0,50).map((sample,i)=><tr key={i}><td>{sample.sensor}</td><td>{aligned?relativeTime((BigInt(sample.timestampNs)+BigInt(imuClock!.offsetToSessionNs!)).toString(),'0'):sample.timestampNs}</td><td>{sample.values.map(n=>n.toFixed(3)).join(', ')}</td></tr>)}</tbody></table></div></details>}<details><summary>{gaps.length} recorded gaps / availability events · {events.length} events total</summary><div className="capture-package-events">{(gaps.length?gaps:events).slice(0,100).map((event,i)=><p className="small" key={i}><strong>{event.type}</strong> · {event.clockId} {event.timestampNs} ns<br/>{event.detail}</p>)}{(gaps.length?gaps:events).length>100&&<p className="small muted">Showing the first 100 events. All events remain in the original package.</p>}</div></details></section>
  {!!manifest.reconstructions.length&&<section className="capture-package-section"><h3><Box size={17}/>Reconstructed on device</h3>{manifest.reconstructions.map((scene,i)=><button className="secondary full" key={scene.path} onClick={()=>onOpenScene(new File([assets.get(scene.path)!],scene.path.split('/').pop()!,{type:'application/octet-stream'}))}>Open reconstructed scene {i+1} · PLY</button>)}<p className="small muted">Each reconstruction uses its own world frame. Separate scans are not automatically aligned.</p></section>}
  <a className="primary full" href={originalUrl||undefined} download={capture.original.name}><Download size={17}/>Download original capture package</a>
 </DialogContent></Dialog>;
}
