'use client';
import {useEffect,useRef,useState} from 'react';
import {Euler,Quaternion,MathUtils} from 'three';
import type {Layer,Vec3,Quat} from '@/lib/recruiser/storage';
import {restoreAlignment,sameAlignment} from '@/lib/recruiser/scene-edits';
import {nudgeLayer,nudgeKey,type NudgeMode} from '@/lib/recruiser/navigation';
import {Switch} from '@/components/ui/switch';
import {Check,Box,Move,RotateCcw,Trash2,Undo2} from 'lucide-react';
export default function LayerInspector({layer,original,previous,onRemove,onApply,onPreview,busy}:{layer:Layer|null;original?:Layer;previous?:Layer;onRemove:()=>void;onApply:(l:Layer)=>void;onPreview:(l:Layer|null)=>void;busy:boolean}){
 const[pos,setPos]=useState<Vec3>([0,0,0]),[rot,setRot]=useState<Vec3>([0,0,0]),[scale,setScale]=useState(1),[mode,setMode]=useState<NudgeMode>('move'),[step,setStep]=useState(.1),[angle,setAngle]=useState(1),[dirty,setDirty]=useState(false);
 const pad=useRef<HTMLDivElement>(null),draft=useRef<Layer|null>(layer);
 function display(l:Layer){draft.current=l;setPos([...l.pose.position]);const e=new Euler().setFromQuaternion(new Quaternion(...l.pose.quaternion),'XYZ');setRot([e.x,e.y,e.z].map(MathUtils.radToDeg) as Vec3);setScale(l.scale)}
 useEffect(()=>{if(layer)display(layer);setDirty(false)},[layer]);
 if(!layer)return <div className="panel-empty"><Box size={28}/><p>Select a layer to inspect its position and provenance.</p></div>;
 const valid=[...pos,...rot,scale].every(Number.isFinite)&&scale>0;
 function preview(l:Layer){display(l);setDirty(true);onPreview(l)}
 function fields(p:Vec3,r:Vec3,s:number){setPos(p);setRot(r);setScale(s);setDirty(true);if([...p,...r,s].every(Number.isFinite)&&s>0){const l={...layer!,pose:{position:p,quaternion:new Quaternion().setFromEuler(new Euler(...r.map(MathUtils.degToRad) as Vec3,'XYZ')).normalize().toArray() as Quat},scale:s,alignment:'manual' as const};draft.current=l;onPreview(l)}}
 function nudge(axis:0|1|2,sign:number,multiplier=1){if(busy||!valid||!draft.current)return;preview(nudgeLayer(draft.current,mode,axis,sign*(mode==='move'?step:angle)*multiplier))}
 function cancel(){display(layer!);setDirty(false);onPreview(null)}
 return <div className="inspector-content"><div className="section-label">SELECTED LAYER <span className="badge">{layer.kind}</span></div><h3 className="truncate">{layer.name}</h3>
 <div className="setting-row"><span>Visible</span><Switch aria-label="Layer visibility" disabled={busy||dirty} checked={layer.visible} onCheckedChange={v=>onApply({...layer,visible:v})}/></div>
 <div className="alignment-flips"><span>Orientation correction</span><div className="button-pair">{([0,2] as const).map(axis=><button className="secondary" disabled={busy||!valid} key={axis} title={axis===0?'Rotate 180° around world X. Converts Y-down / Z-forward camera coordinates to Y-up / Z-back.':'Rotate 180° around world Z.'} onClick={()=>preview(nudgeLayer(draft.current!,'rotate',axis,180))}>Flip {axis===0?'X':'Z'} 180°</button>)}</div><p className="alignment-note">Preview a correction, then Apply or Cancel. Original file transforms are retained; no format-wide flip is applied.</p></div>
 <div className="alignment-recovery"><button className="secondary full" disabled={busy||!original||(!dirty&&sameAlignment(layer,original))} onClick={()=>original&&preview(restoreAlignment(layer,original))}><RotateCcw size={15}/>Reset to imported pose</button><button className="secondary full" disabled={busy||!previous} onClick={()=>previous&&preview(restoreAlignment(layer,previous))}><Undo2 size={15}/>Undo last saved alignment</button><p className="alignment-note">Reset restores this layer’s first saved position, rotation and scale. Embedded GLB transforms stay intact.</p></div>
 <div ref={pad} className="nudge-pad" tabIndex={0} role="group" aria-label="Selected layer nudge controls" onKeyDown={e=>{if((e.target as HTMLElement).matches('input,select,textarea')||busy)return;if(e.key==='Escape'){cancel();e.preventDefault();return}const command=nudgeKey(e.code,mode);if(command){e.preventDefault();e.stopPropagation();nudge(command.axis,command.sign,(e.shiftKey?10:1)*((e.ctrlKey||e.metaKey)?0.1:1))}}}>
 <div className="button-pair"><button className={'secondary '+(mode==='move'?'chosen':'')} aria-pressed={mode==='move'} onClick={()=>{setMode('move');pad.current?.focus()}}><Move size={15}/>Move layer</button><button className={'secondary '+(mode==='rotate'?'chosen':'')} aria-pressed={mode==='rotate'} onClick={()=>{setMode('rotate');pad.current?.focus()}}><RotateCcw size={15}/>Rotate layer</button></div>
 <p>Click here, then use arrow keys and Page Up/Down. Shift: ×10 · Ctrl: ×0.1.</p>
 <p>{mode==='move'?'←/→ X · ↑/↓ −Z/+Z · Page Up/Down +Y/−Y':'←/→ yaw · ↑/↓ pitch · Page Up/Down roll'}. World axes; rotation uses the layer origin.</p>
 <label className="field">{mode==='move'?'Move step · scene units':'Rotation step · degrees'}<input aria-label="Nudge step" type="number" min={.000001} step={mode==='move'?.1:1} value={mode==='move'?step:angle} onChange={e=>{const v=e.target.valueAsNumber;if(Number.isFinite(v)&&v>0)(mode==='move'?setStep:setAngle)(v)}}/></label>
 <div className="nudge-buttons">{(['X','Y','Z'] as const).map((axis,i)=><div key={axis}><button className="secondary" disabled={busy||!valid} onClick={()=>nudge(i as 0|1|2,-1)} aria-label={'Nudge '+axis+' negative'}>−{axis}</button><button className="secondary" disabled={busy||!valid} onClick={()=>nudge(i as 0|1|2,1)} aria-label={'Nudge '+axis+' positive'}>+{axis}</button></div>)}</div></div>
 {([['Position',pos],['Rotation · degrees',rot]] as const).map(([label,values])=><fieldset className="transform-field" key={label} disabled={busy}><legend>{label}</legend><div className="axis-fields">{['X','Y','Z'].map((a,i)=><label key={a}><span className={'axis-'+a.toLowerCase()}>{a}</span><input aria-label={label+' '+a} type="number" step={label==='Position'?.1:1} value={Number.isFinite(values[i])?values[i]:''} onChange={e=>{const arr=[...values] as Vec3;arr[i]=e.target.valueAsNumber;label==='Position'?fields(arr,rot,scale):fields(pos,arr,scale)}}/></label>)}</div></fieldset>)}
 <label className="field">Uniform scale<input type="number" disabled={busy} min={.000001} step={.1} value={Number.isFinite(scale)?scale:''} onChange={e=>fields(pos,rot,e.target.valueAsNumber)}/></label>
 <div className="button-pair"><button className="primary" disabled={busy||!valid||!dirty} onClick={()=>onApply(draft.current!)}><Check size={16}/>Apply alignment</button><button className="secondary" disabled={busy||!dirty} onClick={cancel}>Cancel</button></div><p className="alignment-note">{dirty?'Preview only. Apply saves one scene revision; Cancel restores the saved pose.':'Nudging changes only this layer. Scene history can restore earlier alignments.'}</p>
 <button className="secondary full danger-action" disabled={busy} onClick={onRemove}><Trash2 size={16}/>Remove layer</button>
 <div className="source-details"><span className="section-label">PROVENANCE</span><dl><dt>Alignment</dt><dd className={layer.alignment==='unregistered'?'amber':''}>{layer.alignment}</dd><dt>Source records</dt><dd>{layer.sourceIds.length}</dd><dt>Asset hash</dt><dd className="mono">{layer.blobKey.slice(0,12)}</dd>{Object.entries(layer.provenance).map(([k,v])=><div className="provenance-line" key={k}><dt>{k}</dt><dd>{typeof v==='object'?JSON.stringify(v):String(v)}</dd></div>)}</dl></div></div>
}
