'use client';
import {useEffect,useRef,useState} from 'react';
import type {PreparedFile} from '@/lib/recruiser/export-handoff';
import type {RenderLayer,createSceneEngine} from '@/lib/recruiser/render';
import {House,Orbit,Navigation,Grid3X3,Move,RotateCcw,RotateCw,ChevronUp,ChevronDown,ChevronLeft,ChevronRight,Maximize,Box,Camera,Video,Square} from 'lucide-react';
import {Tooltip,TooltipContent,TooltipTrigger} from '@/components/ui/tooltip';
import {Slider} from '@/components/ui/slider';

export default function SceneViewport({layers,candidateLayers,onLayerError,onPoseChange,onOpen,selectedId,onEngineReady,onCapture}:{onCapture:(file:PreparedFile)=>void;layers:RenderLayer[];candidateLayers:RenderLayer[];onLayerError:(e:{id:string;message:string})=>void;onPoseChange:(p:{position:number[];quaternion:number[];fps:number;objects:number})=>void;onOpen:()=>void;selectedId?:string;onEngineReady:(e:Awaited<ReturnType<typeof createSceneEngine>>|null)=>void}){
 const host=useRef<HTMLDivElement>(null),wrap=useRef<HTMLDivElement>(null),engine=useRef<Awaited<ReturnType<typeof createSceneEngine>>|null>(null);const callbacks=useRef({onLayerError,onPoseChange,onEngineReady});callbacks.current={onLayerError,onPoseChange,onEngineReady};const items=useRef([...layers,...candidateLayers]);items.current=[...layers,...candidateLayers];const[ready,setReady]=useState(false),[generation,setGeneration]=useState(0),[mode,setMode]=useState('orbit'),[grid,setGrid]=useState(true),[error,setError]=useState(''),[points,setPoints]=useState(.018),[speed,setSpeed]=useState(2),[wire,setWire]=useState(false);
 const[recording,setRecording]=useState(false),[stopping,setStopping]=useState(false),[elapsed,setElapsed]=useState(0);const recorder=useRef<MediaRecorder|null>(null);
 useEffect(()=>{if(!recording)return;const started=Date.now(),timer=setInterval(()=>setElapsed(Math.floor((Date.now()-started)/1000)),1000);const unload=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',unload);return()=>{clearInterval(timer);window.removeEventListener('beforeunload',unload)}},[recording]);
 useEffect(()=>()=>{if(recorder.current&&recorder.current.state!=='inactive')recorder.current.stop()},[]);
 async function screenshot(){try{if(!engine.current)throw Error('The viewer is still initializing.');onCapture({blob:await engine.current.screenshot(),name:'recruiser-'+new Date().toISOString().replace(/[:.]/g,'-')+'.png'})}catch(e){setError((e as Error).message)}}
 function record(){if(recorder.current){if(recorder.current.state!=='inactive'){setStopping(true);recorder.current.stop()}return}let stream:MediaStream|null=null,release:()=>void=()=>{},cleanup:()=>void=()=>{};try{if(!engine.current)throw Error('The viewer is still initializing.');if(typeof MediaRecorder==='undefined')throw Error('This browser does not support video recording. Try a current Chromium or Firefox browser.');const capture=engine.current.captureStream();stream=capture.stream;release=capture.release;const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm','video/mp4'].find(m=>MediaRecorder.isTypeSupported(m));const media=new MediaRecorder(stream,{...(mime?{mimeType:mime}:{}),videoBitsPerSecond:8000000}),chunks:Blob[]=[];let size=0;const rendererCanvas=host.current?.querySelector('canvas');const stopWithMessage=(message:string)=>{if(media.state!=='inactive'){setError(message);setStopping(true);media.stop()}};const hide=()=>{if(document.hidden)stopWithMessage('Recording stopped when the tab became hidden. Save the prepared video to keep it.')};const contextLost=()=>stopWithMessage('Recording stopped because the graphics context was lost.');document.addEventListener('visibilitychange',hide);rendererCanvas?.addEventListener('webglcontextlost',contextLost);cleanup=()=>{document.removeEventListener('visibilitychange',hide);rendererCanvas?.removeEventListener('webglcontextlost',contextLost)};recorder.current=media;media.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);size+=e.data.size;if(size>=512*1024*1024&&media.state!=='inactive'){setError('Recording reached 512 MB and was stopped for saving.');setStopping(true);media.stop()}}};media.onerror=()=>{setError('Video recording failed. Any recorded frames will be offered for saving.');if(media.state!=='inactive')media.stop()};media.onstop=()=>{release();cleanup();const type=media.mimeType||chunks[0]?.type||'video/webm';if(chunks.length)onCapture({blob:new Blob(chunks,{type}),name:'recruiser-flight-'+new Date().toISOString().replace(/[:.]/g,'-')+(type.includes('mp4')?'.mp4':'.webm')});else setError('No video frames were recorded.');recorder.current=null;setRecording(false);setStopping(false);setElapsed(0)};media.start(1000);setElapsed(0);setRecording(true);setError('')}catch(e){cleanup();release();stream?.getTracks().forEach(t=>t.stop());recorder.current=null;setError((e as Error).message)}}
 useEffect(()=>{let cancelled=false;setReady(false);setError('');void import('@/lib/recruiser/render').then(({createSceneEngine})=>{if(cancelled)return null;return createSceneEngine(host.current!,(id,message)=>{callbacks.current.onLayerError({id,message});if(id==='viewport'){setError(message);if(message)setReady(false)}},p=>callbacks.current.onPoseChange(p))}).then(e=>{if(!e)return;if(cancelled){e.dispose();return}engine.current=e;callbacks.current.onEngineReady(e);e.setMode(mode);e.setGrid(grid);e.setPointSize(points);e.setSpeed(speed);e.setWireframe(wire);e.setLayers(items.current);callbacks.current.onLayerError({id:'viewport',message:''});setReady(true)}).catch(e=>{if(cancelled)return;setError(e.message||'WebGL2 is unavailable.');callbacks.current.onLayerError({id:'viewport',message:e.message})});return()=>{cancelled=true;engine.current?.dispose();engine.current=null;callbacks.current.onEngineReady(null)}},[generation]);
 useEffect(()=>{engine.current?.setLayers([...layers,...candidateLayers])},[layers,candidateLayers]);
 const action=(label:string,fn:()=>void,icon:React.ReactNode,active=false)=><Tooltip key={label}><TooltipTrigger asChild><button aria-label={label} className={'tool '+(active?'active':'')} onClick={fn}>{icon}</button></TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip>;
 return <div className="viewport" ref={wrap}><div ref={host} className="canvas-host"/><div className="view-top"><div className="view-tag"><span className="crosshair-mark">+</span> WORLD FRAME <span className="dim">/ PERSPECTIVE</span></div><div className="view-tag subtle">Y UP <span className="axis-x">X</span><span className="axis-y">Y</span><span className="axis-z">Z</span></div></div>
 <div className="capture-controls"><button className="capture-button" disabled={!ready} onClick={()=>void screenshot()} aria-label="Save scene screenshot as PNG" title="Save the rendered scene as PNG"><Camera size={16}/><span>Screenshot</span></button><button className={'capture-button '+(recording?'recording':'')} disabled={!ready||stopping} onClick={record} aria-label={recording?'Stop recording and save video':'Record fly-through'} title="Record the viewport at up to 30 fps, without audio. Stop prepares WebM or MP4 for saving. Maximum 512 MB.">{recording?<Square size={15}/>:<Video size={16}/>}<span>{stopping?'Saving…':recording?'Stop · '+Math.floor(elapsed/60)+':'+String(elapsed%60).padStart(2,'0'):'Record'}</span></button></div>
 <div className="viewport-toolbar"><div className="tool-group">{action('Orbit',()=>{setMode('orbit');engine.current?.setMode('orbit')},<Orbit size={18}/>,mode==='orbit')}{action('Mouse fly · full 6DoF',()=>{setMode('fly');engine.current?.setMode('fly')},<Navigation size={18}/>,mode==='fly')}</div><div className="tool-group">{action('Reset lens zoom',()=>engine.current?.resetLens(),<RotateCcw size={18}/>)}{action('Fit whole scene · Home',()=>engine.current?.fit(),<House size={18}/>)}{action('Frame selected',()=>engine.current?.fit(selectedId),<Box size={18}/>)}{action('Reference grid',()=>{setGrid(!grid);engine.current?.setGrid(!grid)},<Grid3X3 size={18}/>,grid)}{action('Wireframe meshes',()=>{setWire(!wire);engine.current?.setWireframe(!wire)},<Move size={18}/>,wire)}{action('Fullscreen',()=>{if(document.fullscreenElement)void document.exitFullscreen();else void wrap.current?.requestFullscreen().catch(()=>setError('Fullscreen is unavailable in this browser.'))},<Maximize size={18}/>)}</div></div>
 {!layers.length&&!candidateLayers.length&&!error&&<div className="scene-empty"><div className="empty-bracket"><Box size={34} strokeWidth={1}/></div><span className="eyebrow">YOUR SPACE, REVISITABLE</span><h2>Give your memories<br/>a place to live.</h2><p>Open a scene. Add a perspective.<br/>Keep building the same world.</p><button className="primary" onClick={onOpen}><Box size={17}/> Open a scene</button><span className="format-line">GLB · PLY · SPLAT</span></div>}
 {error&&<div className="view-error" role="alert"><p>{error}</p>{!ready&&<><p className="small">Your saved files remain available. Close unused 3D tabs and check that browser graphics acceleration is enabled, then retry. Project ZIP export works without the viewer.</p><button className="secondary" disabled={recording||stopping} onClick={()=>setGeneration(g=>g+1)}>Retry graphics</button></>}</div>}
 <div className="view-bottom"><div className="navigation-hint"><span className="small-icon">{mode==='orbit'?<Orbit size={15}/>:<Navigation size={15}/>}</span>{mode==='orbit'?'Drag to orbit · scroll to zoom · right-drag to pan':'Wheel: forward/back · Ctrl: zoom · Shift: strafe · Alt: lift · Ctrl+Shift: roll · drag: look'}</div><span className="view-tag">{ready?'6 DOF':error?'GRAPHICS UNAVAILABLE':'INITIALIZING'}</span></div>
 <div className="view-settings"><label>Point size<Slider aria-label="Point size" min={.002} max={.1} step={.002} value={[points]} onValueChange={v=>{setPoints(v[0]);engine.current?.setPointSize(v[0])}}/></label>{mode==='fly'&&<label>Fly speed<Slider aria-label="Fly speed" min={.1} max={20} step={.1} value={[speed]} onValueChange={v=>{setSpeed(v[0]);engine.current?.setSpeed(v[0])}}/></label>}</div>
 {mode==='fly'&&<div className="touch-flight" aria-label="Touch flight controls">{[['KeyW','Forward',<ChevronUp key="w"/>],['KeyS','Back',<ChevronDown key="s"/>],['KeyA','Left',<ChevronLeft key="a"/>],['KeyD','Right',<ChevronRight key="d"/>],['KeyR','Rise','↑'],['KeyF','Fall','↓'],['KeyQ','Roll left',<RotateCcw key="q"/>],['KeyE','Roll right',<RotateCw key="e"/>],['ArrowUp','Look up','↟'],['ArrowDown','Look down','↡'],['ArrowLeft','Look left','↶'],['ArrowRight','Look right','↷']].map(([key,label,icon])=><button key={String(key)} aria-label={String(label)} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);engine.current?.press(String(key),true)}} onPointerUp={()=>engine.current?.press(String(key),false)} onPointerCancel={()=>engine.current?.press(String(key),false)}>{icon}</button>)}</div>}
 </div>
}
