'use client';
import {useState,useEffect} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Plug,ExternalLink} from 'lucide-react';
import {createWorkerClient,type Capabilities} from '@/lib/recruiser/worker-client';
export function Choice({value,onChange,options,label}:{value:string;onChange:(s:string)=>void;options:(string|[string,string])[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="choice" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=>{const [v,t]=typeof o==='string'?[o,o]:o;return <SelectItem key={v} value={v}>{t}</SelectItem>})}</SelectContent></Select>}
export default function WorkerSettings({open,onOpenChange,onConnect,connected}:{open:boolean;onOpenChange:(b:boolean)=>void;onConnect:(c:ReturnType<typeof createWorkerClient>,caps:Capabilities,url:string)=>void;connected:string}){const[url,setUrl]=useState(connected),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(open)setUrl(connected)},[open,connected]);
 async function connect(){setBusy(true);setError('');try{const c=createWorkerClient({baseUrl:url,bearerToken:token});const caps=await c.capabilities();onConnect(c,caps,url);setToken('');onOpenChange(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="worker-settings-dialog"><DialogHeader><DialogTitle><span className="inline-icon"><Plug size={20}/> 3D processing service</span></DialogTitle><DialogDescription>Your captures are saved on this device. To submit them for 3D reconstruction, connect a compatible processing service. There is no built-in processing service connected.</DialogDescription></DialogHeader><label className="field">Service address<input type="url" placeholder="https://your-worker.example" value={url} onChange={e=>setUrl(e.target.value)}/></label><label className="field">Session token <span className="muted">optional</span><input type="password" autoComplete="off" placeholder="Kept only until you close this page" value={token} onChange={e=>setToken(e.target.value)}/></label><div className="notice">Use the HTTPS address of a running Recruiser API v1 service with browser access (CORS). Connecting checks whether it accepts your camera formats; it does not submit files.</div>{error&&<p className="error-text" role="alert">{error}</p>}<button className="primary" onClick={()=>void connect()} disabled={busy||!url}><Plug size={16}/>{busy?'Checking capabilities…':'Connect service'}</button></DialogContent></Dialog>
}
