import {zipSync,unzipSync,strToU8,strFromU8} from 'fflate';
import {openStore,hashBlob,validateRevision,type Revision,type Source,type SavedJob} from './storage';
const LIMIT=2*1024**3;
export async function exportProject(sceneId:string){const store=await openStore(),scene=await store.getScene(sceneId);const keys=new Set([...scene.sources.flatMap(s=>s.previewBlobKey?[s.blobKey,s.previewBlobKey]:[s.blobKey]),...scene.revisions.flatMap(r=>r.layers.map(l=>l.blobKey)),...scene.jobs.flatMap(j=>Array.isArray(j.candidateLayers)?j.candidateLayers.map((l:{blobKey:string})=>l.blobKey):[])]);const files:Record<string,Uint8Array>={},assets:Record<string,{path:string;sha256:string;byteLength:number}>={};let total=0;
 for(const key of keys){const b=await store.getBlob(key);total+=b.size;if(total>LIMIT)throw Error('This project exceeds the 2 GiB export limit');const path='assets/'+key;files[path]=new Uint8Array(await b.arrayBuffer());assets[key]={path,sha256:key,byteLength:b.size}}
 files['scene.json']=strToU8(JSON.stringify({schemaVersion:1,scene:{id:scene.id,head:scene.head},revisions:scene.revisions,sources:scene.sources,jobs:scene.jobs,assets},null,2));return new Blob([zipSync(files,{level:0}) as BlobPart],{type:'application/zip'});
}
export async function importProject(zip:Blob){if(zip.size>LIMIT)throw Error('Archive exceeds 2 GiB');let total=0;const files=unzipSync(new Uint8Array(await zip.arrayBuffer()),{filter:entry=>{const p=entry.name;if(p.startsWith('/')||p.includes('\\')||p.split('/').includes('..'))throw Error('Unsafe archive path');total+=entry.originalSize;if(total>LIMIT)throw Error('Uncompressed archive exceeds 2 GiB');return true}});
 if(!files['scene.json'])throw Error('Missing scene.json');const data=JSON.parse(strFromU8(files['scene.json']));if(data.schemaVersion!==1||!Array.isArray(data.revisions)||!Array.isArray(data.sources)||!data.assets)throw Error('Unsupported project archive');
 const blobs:{id:string;blob:Blob}[]=[];
 for(const [key,raw]of Object.entries(data.assets)){const a=raw as {path:string;sha256:string;byteLength:number};const bytes=files[a.path];if(!bytes||bytes.length!==a.byteLength)throw Error('Missing or truncated asset');const blob=new Blob([bytes as BlobPart]);if(await hashBlob(blob)!==a.sha256||key!==a.sha256)throw Error('Asset hash mismatch');blobs.push({id:key,blob})}
 const sceneId=crypto.randomUUID(),revisionIds=new Map<string,string>(),sourceIds=new Map<string,string>(),vignetteIds=new Map<string,string>();for(const r of data.revisions){validateRevision(r);revisionIds.set(r.id,crypto.randomUUID())}for(const s of data.sources)sourceIds.set(s.id,crypto.randomUUID());
 const vig=(id:string)=>{if(!vignetteIds.has(id))vignetteIds.set(id,crypto.randomUUID());return vignetteIds.get(id)!};
 const sources:Source[]=data.sources.map((s:Source)=>{if(!data.assets[s.blobKey]||s.byteLength!==data.assets[s.blobKey].byteLength||s.sha256!==s.blobKey)throw Error('Invalid source reference');if(s.previewBlobKey&&!data.assets[s.previewBlobKey])throw Error('Missing preview asset');return {...s,id:sourceIds.get(s.id)!,sceneId,vignetteId:vig(s.vignetteId)}});
 const revisions:Revision[]=data.revisions.map((r:Revision)=>{if(r.parentRevisionId&&!revisionIds.has(r.parentRevisionId))throw Error('Missing parent revision');return {...r,id:revisionIds.get(r.id)!,sceneId,parentRevisionId:r.parentRevisionId?revisionIds.get(r.parentRevisionId)!:null,vignetteIds:r.vignetteIds.map(vig),removedSourceIds:(r.removedSourceIds??[]).map(id=>{if(!sourceIds.has(id))throw Error('Invalid removed capture reference');return sourceIds.get(id)!}),layers:r.layers.map(l=>{if(!data.assets[l.blobKey]||l.sourceIds.some(s=>!sourceIds.has(s)))throw Error('Invalid layer reference');return {...l,sourceIds:l.sourceIds.map(s=>sourceIds.get(s)!),provenance:{...l.provenance,importedSceneId:data.scene.id}}})}});
 const head=revisionIds.get(data.scene.head);if(!head)throw Error('Missing head revision');const revision=revisions.find(x=>x.id===head)!;
 const jobs:SavedJob[]=(data.jobs??[]).map((j:SavedJob)=>({...j,id:crypto.randomUUID(),sceneId,state:'archived',originalJobId:j.id}));await(await openStore()).importAtomic({blobs,sources,revisions,jobs,scene:{id:sceneId,head,title:revision.title,updatedAt:new Date().toISOString()}});return{sceneId};
}
