import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import {KTX2Loader} from 'three/addons/loaders/KTX2Loader.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
import {PLYLoader} from 'three/addons/loaders/PLYLoader.js';
import {flightWheel} from './navigation';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
export type RenderLayer={id:string;name:string;kind:'mesh'|'points'|'gaussian';file:Blob;position:[number,number,number];quaternion:[number,number,number,number];scale:number;visible:boolean};
export async function classifyGeometry(file:Blob,name:string):Promise<'mesh'|'points'|'gaussian'>{
 const ext=name.toLowerCase().split('.').pop();if(ext==='glb'){const h=new DataView(await file.slice(0,12).arrayBuffer());if(h.byteLength<12||h.getUint32(0,true)!==0x46546c67||h.getUint32(4,true)!==2)throw Error('Invalid GLB 2.0 header');return'mesh'}
 if(ext==='splat'){if(!file.size||file.size%32!==0)throw Error('Invalid binary SPLAT record length');return'gaussian'}
 if(ext!=='ply')throw Error('Use a GLB, PLY or SPLAT file.');const text=new TextDecoder().decode(await file.slice(0,262144).arrayBuffer());const end=text.indexOf('end_header');if(!text.startsWith('ply')||end<0)throw Error('Invalid PLY header');const header=text.slice(0,end);if(!/element vertex [1-9]\d*/.test(header))throw Error('PLY has no vertices');
 const props=[...header.matchAll(/^property\s+\S+\s+(\w+)\s*$/gm)].map(x=>x[1]);if(['scale_0','scale_1','scale_2','rot_0','rot_1','rot_2','rot_3','opacity','f_dc_0','f_dc_1','f_dc_2'].every(p=>props.includes(p)))return'gaussian';
 if(/packed_|element chunk|scale_0|rot_0|f_dc_0/.test(header))throw Error('Unsupported Gaussian PLY schema. Export a standard 3DGS PLY.');
 if(!['x','y','z'].every(p=>props.includes(p)))throw Error('PLY requires x, y and z vertices');return /element face [1-9]\d*/.test(header)?'mesh':'points';
}
function createRenderer(){
 let lastError:unknown;
 // Let the browser choose a GPU first; retry without demanding a high-performance device.
 for(const powerPreference of ['default','low-power'] as const){
  try{return new THREE.WebGLRenderer({canvas:document.createElement('canvas'),antialias:false,alpha:false,powerPreference})}
  catch(error){lastError=error}
 }
 throw Error('WebGL2 could not start. '+(lastError instanceof Error?lastError.message:'Graphics acceleration is unavailable.'));
}
export async function createSceneEngine(host:HTMLDivElement,onError:(id:string,message:string)=>void,onPose:(p:{position:number[];quaternion:number[];fps:number;objects:number})=>void){
 const renderer=createRenderer();renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor('#0b131a');renderer.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','3D scene. Drag to orbit; select Fly for six-degree movement.');
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(55,1,.01,100000);camera.position.set(8,6,10);const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.target.set(0,0,0);orbit.update();
 const root=new THREE.Group();scene.add(root);const grid=new THREE.GridHelper(100,100,0x39606c,0x1d303d);grid.position.y=-.005;scene.add(grid);scene.add(new THREE.HemisphereLight(0xd3edff,0x445464,2));const sun=new THREE.DirectionalLight(0xffeed9,3);sun.position.set(6,15,8);scene.add(sun);
 const axes=new THREE.AxesHelper(1.5);scene.add(axes);
 let spark:any=null;const draco=new DRACOLoader().setDecoderPath('/decoders/draco/');const ktx=new KTX2Loader().setTranscoderPath('/decoders/basis/').detectSupport(renderer);const gltf=new GLTFLoader().setDRACOLoader(draco).setKTX2Loader(ktx).setMeshoptDecoder(MeshoptDecoder);
 gltf.manager.setURLModifier(url=>{if(url.startsWith('blob:')||url.startsWith('data:')||url.startsWith('/decoders/'))return url;throw Error('This GLB references an external asset. Re-export it with embedded textures.');});
 const objects=new Map<string,{object:THREE.Object3D;file:Blob;bounds:THREE.Box3}>(),pending=new Map<string,Blob>();let desired:RenderLayer[]=[],dead=false,mode='orbit',speed=2,pointSize=.018,wireframe=false,raf=0,fitOnce=false;
 const keys=new Set<string>();const recordings=new Set<{canvas:HTMLCanvasElement;context:CanvasRenderingContext2D;stream:MediaStream}>();
 function copyRecordingFrames(){for(const r of recordings){const ratio=Math.min(r.canvas.width/renderer.domElement.width,r.canvas.height/renderer.domElement.height),w=renderer.domElement.width*ratio,h=renderer.domElement.height*ratio;r.context.fillStyle='#000';r.context.fillRect(0,0,r.canvas.width,r.canvas.height);r.context.drawImage(renderer.domElement,(r.canvas.width-w)/2,(r.canvas.height-h)/2,w,h)}}
 const dispose=(obj:THREE.Object3D)=>{if('dispose'in obj&&typeof obj.dispose==='function'){obj.dispose();return}obj.traverse((o:any)=>{o.geometry?.dispose();for(const m of Array.isArray(o.material)?o.material:o.material?[o.material]:[]){for(const v of Object.values(m) as any[])if(v?.isTexture){v.source?.data?.close?.();v.dispose()}m.dispose()}})};
 function transform(item:RenderLayer,o:THREE.Object3D){o.position.fromArray(item.position);o.quaternion.fromArray(item.quaternion);o.scale.setScalar(item.scale);o.visible=item.visible;o.updateMatrixWorld(true);o.traverse((x:any)=>{if(x.isPoints)x.material.size=pointSize;if(x.isMesh&&x.material){for(const m of Array.isArray(x.material)?x.material:[x.material])m.wireframe=wireframe}})}
 function bounds(selection?:string){const b=new THREE.Box3();for(const [id,x]of objects){if(!x.object.visible||selection&&id!==selection)continue;b.union(x.bounds.clone().applyMatrix4(x.object.matrixWorld))}return b}
 function fit(selection?:string){const b=bounds(selection);if(b.isEmpty())return;const size=b.getSize(new THREE.Vector3()).length();if(!Number.isFinite(size))return;const center=b.getCenter(new THREE.Vector3());const distance=Math.max(size/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov/2))),.5);camera.position.copy(center).add(new THREE.Vector3(1,.65,1).normalize().multiplyScalar(distance));camera.up.set(0,1,0);camera.lookAt(center);orbit.target.copy(center);camera.near=Math.max(distance/10000,.0001);camera.far=Math.max(distance*100,10000);camera.updateProjectionMatrix();orbit.update();speed=Math.max(size/5,.1)}
 async function load(item:RenderLayer){pending.set(item.id,item.file);let obj:THREE.Object3D|undefined;try{let b:THREE.Box3;
  if(item.kind==='gaussian'){const {SplatMesh,SparkRenderer,SplatFileType}=await import('@sparkjsdev/spark');if(dead)return;if(!spark){spark=new SparkRenderer({renderer});scene.add(spark)}const splat=new SplatMesh({fileBytes:await item.file.arrayBuffer(),fileType:item.name.toLowerCase().endsWith('.splat')?SplatFileType.SPLAT:SplatFileType.PLY});obj=splat;await splat.initialized;b=splat.getBoundingBox();}
  else if(item.name.toLowerCase().endsWith('.glb')){const result=await gltf.parseAsync(await item.file.arrayBuffer(),'');obj=new THREE.Group();obj.add(result.scene);b=new THREE.Box3().setFromObject(obj);}
  else{const geometry=new PLYLoader().parse(await item.file.arrayBuffer());if(!geometry.getAttribute('position')?.count)throw Error('Empty geometry');geometry.computeBoundingBox();b=geometry.boundingBox!.clone();if(item.kind==='points'){obj=new THREE.Points(geometry,new THREE.PointsMaterial({size:pointSize,vertexColors:!!geometry.getAttribute('color'),color:geometry.getAttribute('color')?0xffffff:0x81d7ce,sizeAttenuation:true}))}else{geometry.computeVertexNormals();obj=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:geometry.getAttribute('color')?0xffffff:0xb4d8de,vertexColors:!!geometry.getAttribute('color'),roughness:.75,side:THREE.DoubleSide}))}}
  if(![...b.min.toArray(),...b.max.toArray()].every(Number.isFinite)||b.isEmpty())throw Error('Asset has invalid or empty spatial bounds');
  const current=desired.find(x=>x.id===item.id&&x.file===item.file);if(dead||!current){dispose(obj);return}transform(current,obj);root.add(obj);onError(item.id,'');objects.set(item.id,{object:obj,file:item.file,bounds:b});if(!fitOnce){fitOnce=true;fit()}
 }catch(e){if(obj)dispose(obj);if(!dead)onError(item.id,e instanceof Error?e.message:'Unable to read geometry')}finally{pending.delete(item.id)}}
 function setLayers(layers:RenderLayer[]){desired=layers;for(const [id,x]of objects){if(!layers.some(l=>l.id===id&&l.file===x.file)){root.remove(x.object);dispose(x.object);objects.delete(id)}}for(const item of layers){const found=objects.get(item.id);if(found)transform(item,found.object);else if(!pending.has(item.id))void load(item)}}
 const resize=new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;if(w&&h){renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}});resize.observe(host);
 const keydown=(e:KeyboardEvent)=>{if(e.target instanceof HTMLElement&&(e.target.matches('input,textarea,select')||e.target.isContentEditable))return;if(e.code==='Escape'){keys.clear();renderer.domElement.blur();return}if(document.activeElement!==renderer.domElement)return;if(e.code==='Home'){fit();e.preventDefault()}if(mode==='fly'&&['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','KeyR','KeyF','ShiftLeft','ShiftRight','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){keys.add(e.code);e.preventDefault()}};
 const keyup=(e:KeyboardEvent)=>keys.delete(e.code);const blur=()=>keys.clear();window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('blur',blur);
 const wheel=(e:WheelEvent)=>{if(mode!=='fly')return;e.preventDefault();flightWheel(camera,e,speed)};renderer.domElement.addEventListener('wheel',wheel,{passive:false});const contextmenu=(e:Event)=>{if(mode==='fly')e.preventDefault()};renderer.domElement.addEventListener('contextmenu',contextmenu);
 let drag=false,lastX=0,lastY=0,dragButton=0;const down=(e:PointerEvent)=>{renderer.domElement.focus();if(mode==='fly'){drag=true;dragButton=e.button;lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)}};const move=(e:PointerEvent)=>{if(!drag||mode!=='fly')return;if(dragButton===2){camera.translateX(-(e.clientX-lastX)*speed*.002);camera.translateY((e.clientY-lastY)*speed*.002)}else{camera.rotateY(-(e.clientX-lastX)*.004);camera.rotateX(-(e.clientY-lastY)*.004);}lastX=e.clientX;lastY=e.clientY};const up=()=>{drag=false};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',up);
 let last=performance.now(),lastReport=last,frames=0;function frame(now:number){if(dead)return;const dt=Math.min((now-last)/1000,.05);last=now;if(mode==='orbit')orbit.update();else{const step=speed*dt*(keys.has('ShiftLeft')||keys.has('ShiftRight')?4:1);if(keys.has('KeyW'))camera.translateZ(-step);if(keys.has('KeyS'))camera.translateZ(step);if(keys.has('KeyA'))camera.translateX(-step);if(keys.has('KeyD'))camera.translateX(step);if(keys.has('KeyR'))camera.translateY(step);if(keys.has('KeyF'))camera.translateY(-step);if(keys.has('KeyQ'))camera.rotateZ(dt);if(keys.has('KeyE'))camera.rotateZ(-dt);if(keys.has('ArrowLeft'))camera.rotateY(dt);if(keys.has('ArrowRight'))camera.rotateY(-dt);if(keys.has('ArrowUp'))camera.rotateX(dt);if(keys.has('ArrowDown'))camera.rotateX(-dt)}
 try{renderer.render(scene,camera);copyRecordingFrames()}catch(e){onError('viewport',e instanceof Error?e.message:'Rendering failed');dead=true;return}frames++;if(now-lastReport>750){onPose({position:camera.position.toArray(),quaternion:camera.quaternion.toArray(),fps:Math.round(frames*1000/(now-lastReport)),objects:objects.size});frames=0;lastReport=now}raf=requestAnimationFrame(frame)}raf=requestAnimationFrame(frame);
 const lost=(e:Event)=>{e.preventDefault();dead=true;cancelAnimationFrame(raf);onError('viewport','The graphics context was lost. Retry graphics to rebuild the viewer from your saved scene.')};renderer.domElement.addEventListener('webglcontextlost',lost);
 async function exportComposite(format:'glb'|'ply',ids:string[],unitStatus:string){
  const selected=ids.map(id=>{const loaded=objects.get(id),item=desired.find(l=>l.id===id);if(!loaded||!item||loaded.file!==item.file)throw Error('Wait for all visible layers to finish loading before export.');return {loaded,item}});
  const {exportCompositeGLB,exportCompositeGaussians}=await import('./composite');
  if(format==='glb'){if(selected.some(x=>x.item.kind==='gaussian'))throw Error('GLB export cannot retain Gaussian splats. Use Project ZIP for a mixed composition, or hide splat layers.');return exportCompositeGLB(selected.map(x=>x.loaded.object),unitStatus)}
  if(selected.some(x=>x.item.kind!=='gaussian'))throw Error('Gaussian PLY export requires only Gaussian layers. Use Project ZIP for a mixed composition, or hide other layers.');
  return exportCompositeGaussians(selected.map(x=>x.loaded.object as import('./composite').GaussianObject));
 }
 function screenshot():Promise<Blob>{return new Promise((resolve,reject)=>{try{renderer.render(scene,camera);renderer.domElement.toBlob(blob=>blob?resolve(blob):reject(Error('Screenshot could not be created.')),'image/png')}catch(e){reject(e)}})}
 function captureStream(){const canvas=document.createElement('canvas');if(typeof canvas.captureStream!=='function')throw Error('This browser does not support recording the 3D canvas.');canvas.width=Math.max(2,Math.floor(renderer.domElement.width/2)*2);canvas.height=Math.max(2,Math.floor(renderer.domElement.height/2)*2);const context=canvas.getContext('2d');if(!context)throw Error('Recording canvas is unavailable.');const stream=canvas.captureStream(30),recording={canvas,context,stream};recordings.add(recording);renderer.render(scene,camera);copyRecordingFrames();return {stream,release(){stream.getTracks().forEach(t=>t.stop());recordings.delete(recording);canvas.width=0;canvas.height=0}}}
 return{setLayers,fit,exportComposite,screenshot,captureStream,resetLens(){camera.fov=55;camera.updateProjectionMatrix()},setMode(m:string){mode=m;drag=false;keys.clear();orbit.enabled=m==='orbit';if(m==='orbit'){camera.up.set(0,1,0);orbit.target.copy(camera.position).add(camera.getWorldDirection(new THREE.Vector3()).multiplyScalar(5));orbit.update()}},setGrid(v:boolean){grid.visible=v;axes.visible=v},setSpeed(v:number){speed=v},setPointSize(v:number){pointSize=v;for(const l of desired){const o=objects.get(l.id);if(o)transform(l,o.object)}},setWireframe(v:boolean){wireframe=v;for(const l of desired){const o=objects.get(l.id);if(o)transform(l,o.object)}},press(key:string,on:boolean){on?keys.add(key):keys.delete(key)},dispose(){for(const r of recordings)r.stream.getTracks().forEach(t=>t.stop());recordings.clear();dead=true;cancelAnimationFrame(raf);resize.disconnect();renderer.domElement.removeEventListener('wheel',wheel);renderer.domElement.removeEventListener('contextmenu',contextmenu);orbit.dispose();draco.dispose();ktx.dispose();for(const x of objects.values())dispose(x.object);spark?.dispose();grid.geometry.dispose();(grid.material as THREE.Material).dispose();axes.geometry.dispose();(axes.material as THREE.Material).dispose();renderer.domElement.removeEventListener('webglcontextlost',lost);renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',blur)}};
}
