export type Capabilities={apiVersion:1;worker:{name:string;version:string};inputs:{extension:string;projections:string[];lensProfiles:string[]}[];outputs:string[];maxFileBytes:number;supportsCancellation:boolean};
export type JobStatus={jobId:string;state:string;progress:number|null;message:string;candidate:null|{id:string;baseRevisionId:string;alignmentScore:number|null;alignmentMethod:string;warnings:string[];outputs:{assetId:string;name:string;format:string;pose:{position:[number,number,number];quaternion:[number,number,number,number]};scale:number;sourceIds:string[]}[]}};
export class WorkerError extends Error{constructor(message:string,public status=0,public retryAfter=0){super(message)}}
export function createWorkerClient({baseUrl,bearerToken='',onStatus=()=>{}}:{baseUrl:string;bearerToken?:string;onStatus?:(s:string)=>void}){
 const base=new URL(baseUrl);if(base.protocol!=='https:')throw Error('Use a browser-accessible HTTPS worker address.');if(base.username||base.password)throw Error('Put credentials in the session token field.');base.search='';base.hash='';
 const origin=base.origin;const prefix=base.pathname.replace(/\/$/,'');
 async function request(path:string,init:RequestInit={},binary=false):Promise<any>{const url=new URL(prefix+path,origin);if(url.origin!==origin)throw Error('Worker origin mismatch');let r:Response;try{r=await fetch(url,{...init,credentials:'omit',redirect:'error',signal:init.signal??AbortSignal.timeout(120000),headers:{...(bearerToken?{Authorization:'Bearer '+bearerToken}:{}),...init.headers}})}catch{throw new WorkerError('Worker unreachable. Check HTTPS, CORS and whether the worker is running.')}
 if(!r.ok){let message='';try{message=((await r.json()) as {message?:string}).message??''}catch{}const hints:Record<number,string>={401:'Session token required or expired.',403:'Worker access denied.',413:'Source exceeds the worker size limit.',422:'Worker rejected decoding, calibration or alignment.',429:'Worker busy. Retry after its requested delay.'};const raw=r.headers.get('Retry-After')??'';const retryAfter=/^\d+$/.test(raw)?Number(raw)*1000:Math.max(0,Date.parse(raw)-Date.now())||0;throw new WorkerError(message||hints[r.status]||'Worker request failed ('+r.status+').',r.status,retryAfter)}return binary?r.blob():r.json();}
 async function retry(path:string,init:RequestInit){for(let n=0;;n++){try{return await request(path,init)}catch(e){if(!(e instanceof WorkerError)||n>=2||![0,429,500,502,503,504].includes(e.status))throw e;onStatus('Connection interrupted; retrying the same request…');await new Promise(r=>setTimeout(r,Math.max(e.retryAfter,1000*(n+1))))}}}
 const segment=(s:string)=>encodeURIComponent(s);
 return{
 async capabilities():Promise<Capabilities>{const c=await request('/v1/capabilities');if(c.apiVersion!==1||!c.worker?.name||!Array.isArray(c.inputs)||!c.inputs.every((x:any)=>typeof x.extension==='string'&&Array.isArray(x.projections)&&Array.isArray(x.lensProfiles))||!Array.isArray(c.outputs)||!Number.isFinite(c.maxFileBytes)||c.maxFileBytes<=0)throw Error('Worker does not implement capabilities API v1.');return c},
 async upload(file:Blob,sha256:string):Promise<{assetId:string;sha256:string;byteLength:number}>{const a=await retry('/v1/assets/'+segment(sha256),{method:'PUT',headers:{'Content-Type':'application/octet-stream'},body:file});if(a.sha256!==sha256||a.byteLength!==file.size||typeof a.assetId!=='string')throw Error('Worker asset acknowledgement did not match the original bytes.');return a},
 async submit(payload:Record<string,unknown>,idempotencyKey:string):Promise<{jobId:string;state:string}>{if(!idempotencyKey||payload.apiVersion!==1||!payload.baseRevisionId||!Array.isArray(payload.sources)||!Array.isArray(payload.baseLayers)||!Number.isFinite(payload.frameSamplingSeconds)||Number(payload.frameSamplingSeconds)<=0)throw Error('Invalid grounded reconstruction request');const j=await retry('/v1/jobs',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':idempotencyKey},body:JSON.stringify(payload)});if(typeof j.jobId!=='string'||typeof j.state!=='string')throw Error('Invalid worker job acknowledgement');return j},
 async status(jobId:string):Promise<JobStatus>{const s=await request('/v1/jobs/'+segment(jobId));if(s.jobId!==jobId||!['queued','decoding','registering','reconstructing','review','failed','cancelled'].includes(s.state)||s.progress!==null&&(!Number.isFinite(s.progress)||s.progress<0||s.progress>1))throw Error('Invalid worker status response');if(s.state==='review'&&(!s.candidate||!Array.isArray(s.candidate.outputs)||!s.candidate.baseRevisionId))throw Error('Worker returned no reviewable candidate');return s},
 async asset(assetId:string):Promise<Blob>{return request('/v1/assets/'+segment(assetId),{},true)},
 async cancel(jobId:string){const r=await request('/v1/jobs/'+segment(jobId)+'/cancel',{method:'POST'});if(r.state!=='cancelled')throw Error('Cancellation requested; worker has not acknowledged stopping.');return r},
 };
}
