import 'fake-indexeddb/auto';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {openStore,identityPose,type Revision,type Source} from '../../lib/recruiser/storage';
import {exportProject,importProject} from '../../lib/recruiser/archive';
import {zipSync,strToU8} from 'fflate';

test('revisions are atomic, retries idempotent, and archive preserves bytes and capture occurrences',async()=>{
 const s=await openStore();const bytes=new Blob(['original capture bytes']);const b=await s.putBlob(bytes);const proxy=await s.putBlob(new Blob(['compatible preview bytes']));const id=crypto.randomUUID();const source:Source={id:crypto.randomUUID(),sceneId:id,sha256:b.sha256,blobKey:b.blobKey,name:'capture.insp',mime:'application/octet-stream',byteLength:bytes.size,importedAt:new Date().toISOString(),captureTime:null,previewBlobKey:proxy.blobKey,previewName:'preview.mp4',previewMime:'video/mp4',projection:'dual-fisheye',lensProfile:'insta360-air',vignetteId:crypto.randomUUID()};await s.saveSource(source);await s.saveSource({...source,id:crypto.randomUUID(),vignetteId:crypto.randomUUID()});
 const r:Revision={id:crypto.randomUUID(),sceneId:id,parentRevisionId:null,worldFrameId:crypto.randomUUID(),unitStatus:'unknown',createdAt:new Date().toISOString(),title:'Persistence specimen',vignetteIds:[source.vignetteId],layers:[{id:crypto.randomUUID(),sourceIds:[source.id],name:'specimen.ply',kind:'gaussian',blobKey:b.blobKey,pose:identityPose(),scale:2,visible:true,alignment:'manual',provenance:{test:true}}]};
 await s.appendRevision(id,null,r);await s.appendRevision(id,null,r);assert.equal((await s.getScene(id)).revisions.length,1);
 const a={...r,id:crypto.randomUUID(),parentRevisionId:r.id},c={...r,id:crypto.randomUUID(),parentRevisionId:r.id};const updates=await Promise.allSettled([s.appendRevision(id,r.id,a),s.appendRevision(id,r.id,c)]);assert.equal(updates.filter(x=>x.status==='fulfilled').length,1);assert.equal(updates.filter(x=>x.status==='rejected').length,1);assert.equal((await s.getScene(id)).revisions.length,2);
 const exported=await exportProject(id),imported=await importProject(exported),restored=await s.getScene(imported.sceneId);assert.notEqual(restored.id,id);assert.equal(restored.revisions.length,2);assert.equal(restored.sources.length,2);assert.notEqual(restored.sources[0].id,restored.sources[1].id);assert.equal(await(await s.getBlob(restored.sources[0].blobKey)).text(),'original capture bytes');assert.equal(await(await s.getBlob(restored.sources[0].previewBlobKey!)).text(),'compatible preview bytes');assert.equal(restored.sources[0].previewName,'preview.mp4');assert.equal(restored.revision.layers[0].kind,'gaussian');assert.equal(restored.revision.layers[0].scale,2);assert.deepEqual(restored.revision.layers[0].pose,r.layers[0].pose);
});
test('archive rejects path traversal and corrupt hashes without creating a scene',async()=>{const s=await openStore();const before=(await s.listScenes()).length;await assert.rejects(()=>importProject(new Blob([zipSync({'../bad':strToU8('bad')}) as BlobPart])),/Unsafe/);const bad={schemaVersion:1,scene:{id:'x',head:'x'},revisions:[],sources:[],assets:{bad:{path:'assets/bad',sha256:'bad',byteLength:3}}};await assert.rejects(()=>importProject(new Blob([zipSync({'scene.json':strToU8(JSON.stringify(bad)),'assets/bad':strToU8('bad')}) as BlobPart])),/hash/);assert.equal((await s.listScenes()).length,before)});
